name: SAST
permissions:
  contents: read

on:
  push

jobs:
  semgrep:
    name: Scan Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:1.21
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - run: semgrep ci
        env:
          # Semgrep Rules
          # https://github.com/returntocorp/semgrep-rules
          SEMGREP_RULES: >-
            p/security-audit
            p/secrets
  gitleaks:
    name: Scan gitLeaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e         #v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
